### ISSUE TITLE
KeyError thrown from 'children' generator in Process when iterating events

### ISSUE THREAD

**Issue by john-corcoran** [carbonblack/cbapi-python#102]
Hi,

For the first time in processing many thousands of event objects, I've seen a KeyError thrown when iterating child events from a process, as follows:

```
File "mycode.py", line 160, in mycode
    for event in process.all_events_segment:
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packa
ges\cbapi\response\models.py", line 2479, in all_events_segment
    list(self.children) + list(self.regmods) + list(self.crossprocs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packa
ges\cbapi\response\models.py", line 2447, in children
    "md5": child["process_md5"],
KeyError: 'process_md5'
```

Can logic be added to substitute a missing key will a null/placeholder value, or will this cause issues later in the chain?

This was encountered using cbapi 1.3.4 on Python 3.6.4 (64bit) on Windows 7.

**Comment by jgarman** [comment]
Thanks to @gnofs , we have a fix for this that will be part of the next cbapi release. Targeting the end of this week (February 2).

Relevant commit is 45fb22b0c00377868679fbfc14aa8bb24834aa96
