### ISSUE TITLE
Problem importing RUN_INMEMORY_CODE rules

### ISSUE THREAD

**Issue by dbarzon** [carbonblack/cbapi-python#106]
Hi,
 thanks for this great tool.
I'm extending policy-operation.py to let me import bulk rules from a CSV.
Everything's working fine except when I try to import rules whose operation is "RUN_INMEMORY_CODE".
It doesn't seem to be related to my code as I'm having the same problem using your json rule importer.
Am I doing anything wrong?
Sample JSON rule:
```
{
      "application": {
        "type": "NAME_PATH",
        "value": "test.exe"
      },
      "operation": "RUN_INMEMORY_CODE",
      "action": "DENY"
}
```
This is working with **all** other operations (RUN, NETWORK, MEMORY_SCRAPE, ect)

**Comment by jgarman** [comment]
I've replicated the issue locally. I'll report it to our backend API developers to fix in the product.
