### ISSUE TITLE
Effects of increasing page size from 100 for large queries

### ISSUE THREAD

**Issue by proteann** [carbonblack/cbapi-python#110]
Hi All,

Working with the CB Response API I have noticed that the the default page size is 100. Are there any effects of increasing it from this number (say overloading of the server)? 

I am running queries with very large results and I notice the performance tanking over 30th page (takes around 16 seconds to pull one page). Is increasing page size a workaround for this?

Apologies if this is not the right stream to post this.

Thanks
Harish

**Comment by jgarman** [comment]
You can absolutely try experimenting with page size to enhance speed - I wouldn't go past 1,000 as you may encounter server timeouts with a large page size.
