### ISSUE TITLE
Requests for many Alerts timeout / take a long time.

### ISSUE THREAD

**Issue by h1lly** [carbonblack/cbapi-python#111]
Iterating over a large set of alerts returned by query ```alert_query = cb_connection.select(Alert).where(query)``` has proved problematic recently as any request for upwards of 100 alert objects to the server would often timeout and has even resulted in the service being made unavailable for a couple of minutes due to what I assume is the operation's taxing nature on the backend.

I have found a fix that appears to not be quite so taxing on the backend, however it would require the API version for requesting alerts to be bumped from v1 to v2 ```Alert.urlobject = '/api/v2/alert'```. I've not created a pull request as I am not sure what impact this change may have on support for older version of Carbon Black.

**Comment by h1lly** [comment]
Though this does fix the request for alerts, it causes issues when actions are taken on alerts (e.g. resolve 
 an alert)

**Comment by zacharyestep** [comment]
Fixed in master.
