### ISSUE TITLE
Joining computer_count from a modload

### ISSUE THREAD

**Issue by geekscrapy** [carbonblack/cbapi-python#112]
Currently dev'd a script which takes a process, gets the modloads and then prints the computer_count associated with the modload by calling "modload".binary. This join however takes on average 10/20 secs to return the binary object.

A simplified version of what I am doing is below.

Is there anyway to sped this up?

```
for ml in p.modloads:
	ebin = ml.binary

	computer_count = ebin.frequency.computer_count

	print('path={}'.format(ml.path), end=', ')
	print('computer_count={}'.format(computer_count))
```

**Comment by zacharyestep** [comment]
There must be too many underlying api calls happening. I'm going to try to take a a deepdive on this - if you could enable requests level debugging and send the logs to dev-support@carbonblack.com that would be great.  Also, consider using facets for this - I think it could get around this issue for use cases like this and possibly improve performance. like so (taken from cb-reporting project in this organization) `  # build a list of hostname/filepath facets for this process-binary-by-md5
        facets = self.cb.select(Process).where("process_md5:" + process.process_md5).facets()
        filepaths = [{"filepath": e['name'], "percentage": e['ratio']} for e in facets.get('path_full')]
        hostnames = [{'hostname': e['name'], 'percentage': e['ratio']} for e in facets.get('hostname')]
`

**Comment by avanbrunt-cb** [comment]
Closing due to outdated status. Please reopen if still a concern
