### ISSUE TITLE
CbLRManagerBase sessions tracking

### ISSUE THREAD

**Issue by jjfallete** [carbonblack/cbapi-python#113]
There appears to be an issue with the CbLRManagerBase's session tracking. More specifically, it does not appear to 'see' that sessions exist (including, from what I've tested, both active and timeout sessions).

This API code:
```
print '_sessions: ' + str(c.live_response._sessions)  
print '_session_lock: ' + str(c.live_response._session_lock)  
print '_keepalive_sessions: ' + str(c.live_response._keepalive_sessions)  
```
 

Outputs:
```
_sessions: {}
_session_lock: <_RLock owner=None count=0>
_keepalive_sessions: False
```

 
Notice that _sessions is empty, despite (timeout) sessions existing if I use the "session list"  command in the CbLR console.

Also, if I use c.live_response.close_session(sensor_id, session_id) with valid ID's from the "session list" command, I am able to properly these (active/timeout) sessions manually.

See: [community.carbonblack.com/thread/9085](http://community.carbonblack.com/thread/9085)

**Comment by avanbrunt-cb** [comment]
Closing due to outdated status. Please reopen if still a concern
