### ISSUE TITLE
Cannot find credential profile issue

### ISSUE THREAD

**Issue by p3nreel** [carbonblack/cbapi-python#120]
Hello All, I have recently installed Carbon Black Surveyor on an Ubuntu Desktop 18.04 system. I am following the instructions on installing/configuring the CB API from https://cbapi.readthedocs.io/en/latest/getting-started.html to work with our CB Response tool. When I get to the "Your First Query"section, I am getting the error below when trying in python and python3. I found a similar issue from another post (https://github.com/carbonblack/cbapi-python/issues/74) and tried both solutions that (Solution 1: pip install request[security]) (Solution 2: Reinstall API) and neither worked. The credential file is located in path /etc/carbonblack/credentials.response. Any thoughts what could be causing this? Thanks in advance.
![cbr](https://user-images.githubusercontent.com/19589960/44168189-62f06a00-a09e-11e8-80c4-a9ae328697a6.JPG)

**Comment by jgarman** [comment]
My first thought is that you ran `python` as an unprivileged user. Does that user have access to the `/etc/carbonblack/credentials.response` file? Try creating the credentials file in the user's home directory (`~/.carbonblack/credentials.response`) instead

**Comment by p3nreel** [comment]
Thanks for the quick response. I changed the file permission so the user can access. I also copied the credential file to the path you recommended getting the errors below. 
![capture](https://user-images.githubusercontent.com/19589960/44173670-9935e580-a0ae-11e8-864c-96b6ab58b858.JPG)

**Comment by jgarman** [comment]
Remove the `/#/login` from the URL in the credential file. It should just be `https://servername`

Python3 is failing because `cbapi` isn't installed in python3. You can use `pip3 install cbapi` if you want to install in the default python3 site-packages directory.

**Comment by jgarman** [comment]
Great to hear! Let us know if you have any further questions - you can also email us at dev-support@carbonblack.com.
