### ISSUE TITLE
document event types and the event api

### ISSUE THREAD

**Issue by atkinsj** [carbonblack/cbapi-python#125]
The [job based API documentation ](https://cbapi.readthedocs.io/en/latest/live-response.html#job-based-api) references a full event API which seems completely undocumented. I can see [here](https://github.com/carbonblack/cbapi-python/blob/d78e6bdfdc951dd69102de2d205db50dbf7fffb7/src/cbapi/response/models/tagged_event.yaml#L11) that there are some event types I could subscribe to but the list isn't exhaustive.

Is this documented anywhere? This feature would be really useful.

**Comment by atkinsj** [comment]
It also seems to require a RabbitMQ host but it's unclear if that's something hosted by CB or that I need to set-up.

**Comment by zacharyestep** [comment]
Hi, Documentation for this "API" is found here:
https://developer.carbonblack.com/reference/enterprise-response/message-bus/
