### ISSUE TITLE
Can't figure out how to pass creds in programtically

### ISSUE THREAD

**Issue by punkrokk** [carbonblack/cbapi-python#132]
Extending #56 if I use a vault or keystore - I can't figure out how to pass in creds without the "enforced" creds file. Am I missing something? 

I also am unable to write tests for my classes that implement this package because of the creds file requirement. cc @momohossain @RyPeck

**Comment by jgarman** [comment]
You can actually do that now. It's not well documented because we don't want to encourage users to embed API tokens in their scripts, but your use case is a great example of where that may fall down.

Here's an example how to do this with the `CbResponseAPI` object:

```c = CbResponseAPI(url="https://172.22.10.16", ssl_verify=False, token="abcd")```

**Comment by momohossain** [comment]
To add on about the tests, I believe when I passed non-real values into the enforced credentials file (to perform unit testing), the cpapi package tried to authenticate using the non-real values, and I couldn't get it to not try to authenticate. Since I could not get past the authentication, I could not run unit tests.

**Comment by RyPeck** [comment]
Quick [read](https://github.com/carbonblack/cbapi-python/blob/54890df0b6b1dae0b00913f2ae56df41377056aa/src/cbapi/connection.py#L221) it looks like you need to set `url` alongside `token`. @momohossain did you pass both of these parameters to `CbResponseAPI`?

**Comment by momohossain** [comment]
I submit all the values in the correct format, but the values I submitted were values I knew would not pass the authentication.  I would like to know if there is either a way to disable authentication (so I can run unit tests), or for me to mock the endpoint(s) that authenticate the credentials so my unit tests think the fake credentials authenticated correctly and proceed to running the tests that I've written.

**Comment by jgarman** [comment]
I'm not sure I understand - are you running unit tests on the `cbapi` module itself, or are you running integration tests with a valid Cb (Response I assume?) server or account? If you're doing the latter, you should have legit credentials for that server. The authentication isn't a complex flow; it's just setting an HTTP header field, which, if you're doing mock tests, can be safely ignored.

**Comment by punkrokk** [comment]
Neither - with our class that wraps your sdk for our partner integrations

Cheers,

JP

**Comment by jgarman** [comment]
I guess I'm still confused - there is a way to pass in credentials in the constructor, which should handle the issue where credentials can't be stored in a separate file. If you're controlling the server side (ie. mocking the responses from the Carbon Black side), you can safely ignore the `X-Auth-Token` header sent by `cbapi` for each request.

**Comment by momohossain** [comment]
If we want to be able to mock the response, don't we need to also be able to mock the endpoint where the HTTP request is being made?

**Comment by RyPeck** [comment]
[requests-mock](https://requests-mock.readthedocs.io/en/latest/) is your friend here if you want to go that route.

**Comment by atkinsj** [comment]
This doesn't work because the check for a profile occurs before the check for a url and token:

https://github.com/carbonblack/cbapi-python/blob/master/src/cbapi/auth.py#L68

I think it's admirable to discourage passing in tokens in code but this breaks a lot of common use cases in 2019 where the token comes from the environment (AWS Lambda, Heroku, GKE, etc).

**Comment by jgarman** [comment]
This is a really good point - thank you. We'll take a look at creating a way to pass credentials via environment variables.

**Comment by zacharyestep** [comment]
Closing this after closing related PR that provides this as a feature.

**Comment by punkrokk** [comment]
Thanks for the quick response guys. @momohossain will be greatful when he sees this.

**Comment by momohossain** [comment]
Yes, thank you.  If I could mock the authentication and the endpoints, it would be much easier to run unit tests on my end.

**Comment by RyPeck** [comment]
Related PR is https://github.com/carbonblack/cbapi-python/pull/136
