### ISSUE TITLE
Syntax error in API docs on Facets 

### ISSUE THREAD

**Issue by quincy7386** [carbonblack/cbapi-python#140]
There is a syntax error on the page of the API docs:
https://cbapi.readthedocs.io/en/latest/response-examples.html#facets

It has:
`print("%15s: %5s%% %s" % (entry["name"][:15], entry["ratio"], u"\u25A0"*(int(entry["percent"])/2)))`

When it should be (moving the *int* outside of the parens):
`print("%15s: %5s%% %s" % (entry["name"][:15], entry["ratio"], u"\u25A0"*int((entry["percent"])/2)))`

**Comment by emitreva-cb** [comment]
This was fixed with the new release 1.7.4, thank you for pointing that out.
