### ISSUE TITLE
/api/v1/binary/(md5) returns 404, but /api/v1/binary/(md5)/summary and /icon don't

### ISSUE THREAD

**Issue by atkinsj** [carbonblack/cbapi-python#141]
Hey folks,

Strange one. I have a script that queries for binaries observed, extracts the md5 and then attempts to download them. A significant portion (>30%) of binaries returned by this search return a 404 when I attempt to hit `/api/v1/binary/(md5)`:

```<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

if I hit /api/v1/binary/(md5)/summary then I get a summary as expected and if I hit /icon/ I get the icon returned.

How is it possible that the icon and summary is present but the binary itself isn't?

**Comment by atkinsj** [comment]
Also, copied_mod_len matches orig_mod_len which I assume means it successfully copied it?

**Comment by jgarman** [comment]
There is a process in the Cb Response server to purge 'old' binaries from the module store. The metadata for the binary (including the icon) remains, as you experienced, but the binary itself is removed.

If you're running the Cb Response server on-premise, the `cb.conf` file contains some options to control this purging behavior. The Cb Response admin guide should have some details on how to adjust this behavior.

**Comment by atkinsj** [comment]
I'm not convinced that's what's happening here. We're running the cloud CBR, not on-prem, fwiw.

These are binaries that have been obserbed within the last week and I'm pulling them chronologically, so I'll successfully get 50 binaries, get a 404 on one, successfully get 40 more. It seems unlikely this is a result of aging?

**Comment by jgarman** [comment]
Most likely, not aging in that case. I would open a support ticket to track down what's going on. The API is the same thing that powers the 'download' button in the UI, so double check that the download button also gives you a 404- if that's the case, then open up a support ticket to track down the root cause.

**Comment by atkinsj** [comment]
Yeah, confirmed that the download button also doesn't work. I'll throw in a ticket, thanks.
