### ISSUE TITLE
Provide credentials generation bin for psc

### ISSUE THREAD

**Issue by zacharyestep** [carbonblack/cbapi-python#149]
There is no equivalent to cbapi-<product> configure for the new psc namespace, resulting in runtime problems for clients who cannot or do not know how to create .carbonblack/credentials.psc on their own.  Cbapi-defense creates credentials.defense should be credentials.psc., now.

**Comment by zacharyestep** [comment]
We will also need to update the developer website and read the docs to reflect the changes in operation, otherwise novices will get tripped up when trying to follow along.

**Comment by avanbrunt-cb** [comment]
This has been implemented and released https://github.com/carbonblack/cbapi-python/blob/master/setup.py#L60
