### ISSUE TITLE
TypeError: unsupported format string passed to dict.__format__

### ISSUE THREAD

**Issue by seanmcfeely** [carbonblack/cbapi-python#161]
You're trying to pass a dictionary object to format here:

```
  File "/data/home/smcfeely/.local/lib/python3.6/site-packages/cbapi/query.py", line 34, in one
    raise MoreThanOneResultError(message="0 results for query {0:s}".format(self._query))
TypeError: unsupported format string passed to dict.__format__
```
Could you add a \_\_str__ function to BaseQuery or whatever you want to do to fix this? Thanks!

**Comment by avanbrunt-cb** [comment]
Thanks for the catch! We have fixed this with https://github.com/carbonblack/cbapi-python/pull/187
