### ISSUE TITLE
[ThreatHunter] Assign a value to process_username when no value exists

### ISSUE THREAD

**Issue by keithmccammon** [carbonblack/cbapi-python#163]
Some ThreatHunter processes do not have a process_username for reasons unknown. When this attribute does not exist, assign it a value so that it doesn't raise an exception. 

This is close to a duplicate of https://github.com/carbonblack/cbapi-python/issues/21, but is manifesting in ThreatHunter and the process_username attribute (vs. username in the Response model).

**Comment by avanbrunt-cb** [comment]
This is an API issue please open a support case with VMware Carbon Black. We've also moved the Carbon Black Cloud functionality to https://github.com/carbonblack/carbon-black-cloud-sdk-python
