### ISSUE TITLE
live response api does not honor cancel command status

### ISSUE THREAD

**Issue by averma-cb** [carbonblack/cbapi-python#164]
In live_response_api.py, _poll_command method calls poll_status of for "{cblr_base}/session/{0}/command/{1}" call.

The poll_status keeps on polling command status and looking for desired status as "complete".
However, it is possible for command status to be set to CANCEL and in that case, the loop will continue (for the defined timeout) and will push out session close request eventually.

issue reported here is to handle CANCEL status response to gracefully terminate the loop (for customer having high time_out values)

For a customer, the timeout is set to 1800 when they are using "create_process" through api. After the command was posted (_lr_post_command), the session was closed (by a different thread which was using same session/sensor but encountered an error and the api hence closed the session). 
The potential response from server for this thread for any in-progress command is "cancel" instead of "complete". The customer ended up polling the server.
 
(There is a another potential bug associated with the server as well, where two different api can post-new-command and close-session at the same time and server keeps the command in queue as pending --  being investigated separately).

**Comment by averma-cb** [comment]
For CB-Internal:
EA-14466 is the original EA
CB-27507 has been raised as a parallel investigation related to the issue.
CB-27499 has been raised as a parallel investigation related to the EA.

**Comment by avanbrunt-cb** [comment]
Closing as this is being managed through an EA
