### ISSUE TITLE
"No organization key specified"

### ISSUE THREAD

**Issue by asmartin95** [carbonblack/cbapi-python#168]
In cbapi 1.4.5, a check was added in the __init__ call of CbThreatHunterAPI (line 25-26 of file rest_api.py) to check if 'org_key' is in credentials. However if you are instantiating the client with a set of kwargs it never pops off the org_key from the kwargs in the BaseApi __init__, it only pops off url and token (line 219-227 of file connection.py). So if you instantiate a client with kwargs instead of a credentials file you will always get the No organization key specified even when passing it in to the constructor.

**Comment by avanbrunt-cb** [comment]
Thanks for the feedback! I believe this has now been addressed https://github.com/carbonblack/cbapi-python/blob/master/src/cbapi/connection.py#L219-L222
