### ISSUE TITLE
cbapi should allow more than 15 children fetch

### ISSUE THREAD

**Issue by averma-cb** [carbonblack/cbapi-python#175]
it was found that there is possibility for /api/v1/process to pass rows for children count based on query parameter "children"

So, a request http://xxx/api/v1/process/YYY/0?children=100 would return max of 100 children instead of default 15. The restriction works well for UI, however, cbapi should have a way to pass this parameter if customer is willing to do so.

walk_children.py in example script used to traverse all children of a process example:

python walk_children.py --process XXX-XXX-XXX-XXX --verbose
would run down all the children of the processes, however at depth 0, the count would be limited to 15.

PS: Issue is not raised to fix walk_children.py (its an example script on how to use cbapi) , The issue being reported is inability to utilize query param children when using cbapi to perform search.

On hacking the cbapi connection.py to hard-code adding "?children=100" in all http_request sent, I was able to get more children (PS: This is not a solution proposed)

Test Result:

Original cbapi:

[root@aman walk_children]# cat file.out_original | grep depth | rev | cut -d" " -f1 | sort | uniq -c
COUNT DEPTH
 15 0
 59 1
 87 2
 21 3
 11 4
 6 5
 2 6

After adding hack in connection.py 

[root@aman walk_children]# cat file2.out | grep depth | rev | cut -d" " -f1 | sort | uniq -c
COUNT DEPTH
 89 0
 603 1
 1096 2
 138 3
 66 4
 20 5
 6 6
 (For above tests I added following line in visitor method in walk_children.py)

`print ("Working with {0}  at depth {1}".format(proc.process_name, depth));`

CB Internal : CB-28123

**Comment by avanbrunt-cb** [comment]
Fixed and released https://github.com/carbonblack/cbapi-python/pull/176
