### ISSUE TITLE
Federated console: Add CredentialStore source from Unified View URL

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cbapi-python#19]
The Unified View console can provide API keys & URLs for all servers it manages. We could use this as a CredentialStore to automatically provide profiles for these servers

**Comment by garyjblackwell** [comment]
Any progress on this enhancement?  Is there any way to run CBAPI Python queries to all Carbon Black Response Cloud instances at one time like the Unified View console?

**Comment by avanbrunt-cb** [comment]
Closing due to outdated status. Please reopen if still a concern
