### ISSUE TITLE
Legacy cbapi function watchlist_enable_action

### ISSUE THREAD

**Issue by thepcn3rd** [carbonblack/cbapi-python#2]
With the legacy cbapi.py inside of the function watchlist_enable_action the url needs to be changed from the following:

url = "%s/util/v1/watchlist/%d/action" % (self.server, watchlist_id)

to:

url = "%s/api/v1/watchlist/%d/action" % (self.server, watchlist_id)

With this change it is then usable.  

Thank you,
Leon Trappett

**Comment by jgarman** [comment]
Sorry I missed this for 0.9.2 - it will be included in the next release. Thanks for  reporting this!
