### ISSUE TITLE
[BUG] max_children flag not respected in walk_children()

### ISSUE THREAD

**Issue by mtmcgrew** [carbonblack/cbapi-python#211]
**I am seeing this behavior on: (please complete the following information):**
 - OS: OS X
 - Carbon Black Product: CB Response API
 - Python Version: 2.7

**Describe the bug**
When setting the --children in the walk_children.py example script the first query to the processes API does set the `children` parameter properly, but any subsequent call for each child process sets the `children` parameter to the default 15. This causes problems because if a child process has more than 15 of its own children they will not all be enumerated and displayed.

**Steps to Reproduce**
Run the walk_children.py with the --verbose flag and set the children to a non default value. You will see that the first API call sets the children properly but any subsequent call does not.
 
**Expected behavior**
The `children` parameter is set for all API calls.

**Comment by avanbrunt-cb** [comment]
Closing as PR was merged
