### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by garyjblackwell** [carbonblack/cbapi-python#218]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: Windows 10
 - Carbon Black Product: CB Response
 - Python Version: 3.7.4

**Describe the bug**
When I run get_reg_autoruns.py, it says:

_File "get_reg_autoruns.py", line 26, in <module>
    from cbapi.event import on_event, registry
  File "C:\Python\lib\site-packages\cbapi\event.py", line 4, in <module>
    import Queue
ModuleNotFoundError: No module named 'Queue'_

**Steps to Reproduce**
Steps to reproduce the behavior (Provide a log message if relevant):
1. Go to folder where get_reg_autoruns.py is in a command line.
2. Run python get_reg_autoruns.py.

**Expected behavior**
A list of registry entries and values as indicated in the script.

**Screenshots**
If applicable, add screenshots or code to help explain your problem.
![image](https://user-images.githubusercontent.com/62297277/76870202-c8d74180-683f-11ea-8c50-c4151b4b494e.png)

**Comment by valoulou** [comment]
Hi @garyjblackwell,

Did you try to change `import Queue ` by `import queue` ?

Could be a quickfix.

Thanks,

**Comment by garyjblackwell** [comment]
Yes, I changed the capital Q to a lower case q.  it gets me a little further, but it is still not working.

**Comment by avanbrunt-cb** [comment]
@garyjblackwell You'll have to provide more error details if you want to reopen the issue

**Comment by garyjblackwell** [comment]
Does this help?
(base) C:\Users\GaryBlackwell\Documents\cbapi-python\examples\response\event>python get_reg_autoruns.py
Traceback (most recent call last):
  File "get_reg_autoruns.py", line 29, in <module>
    from cbapi.response import sensor_events, event
  File "C:\Users\GaryBlackwell\anaconda3\lib\site-packages\cbapi\response\sensor_events.py", line 36, in <module>
    type=None),
  File "C:\Users\GaryBlackwell\anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 717, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

**Comment by avanbrunt-cb** [comment]
This script likely only supports python2 as it was written quite awhile ago. We don't currently plan on updating the script for python3

**Comment by garyjblackwell** [comment]
Understood, thanks
