### ISSUE TITLE
[BUG] Tried to modify user property but it didn't work

### ISSUE THREAD

**Issue by mbhatt1** [carbonblack/cbapi-python#219]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: Mac Catalina (python script)
 - Carbon Black Product: CB Response
 - Python Version: 3.75

**Describe the bug**
Tried to do
```
for u in cb.select(User):
    if u.email == 'someemail':
        u.permissions['some permissions'] = True
        u.save()
```

It ran but the permissions didn't get updated in the UI. Have GA. 

**Steps to Reproduce**
Above section

**Expected behavior**
Permissions being changed.

**Comment by mbhatt1** [comment]
Am I doing something wrong?

**Comment by avanbrunt-cb** [comment]
Sorry for the delayed response. If this error is still occurring for you, can you open a support ticket with Carbon Black for further investigation.
