### ISSUE TITLE
[BUG] Importing ABC from collections directly was deprecated in Python 3.4 and will be removed in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [carbonblack/cbapi-python#225]
**I am seeing this behaviour on: (please complete the following information):**
 - Carbon Black Product: [e.g. CB Protection, CB Defense]
 - Python Version: 3.8

**Describe the bug**

Importing ABC from collections directly was deprecated in Python 3.4 and will be removed in Python 3.10. Use collections.abc in Python 3.

```
tests/requests_cache/backends/storage/dbdict.py
9:from collections import MutableMapping
```

**Comment by avanbrunt-cb** [comment]
Thanks for the PR. We are looking into this issue which also affects one of our other libraries as well
