### ISSUE TITLE
Create enhanced error reporting/recording capability

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cbapi-python#23]
- add more information to exceptions:
  - version of the server
  - exact HTTP request/response
- save exceptions to a local sqlite database
- output a uuid to the screen for any errors
- small tool to print out the error
- encryption utility to build and send an error report. requirements:
  - needs to function off-network (cut & paste, ascii armored)
  - encrypted output (we embed our error reporting public key in the cbapi?)

**Comment by avanbrunt-cb** [comment]
Closing due to outdated status. Please reopen if still a concern
