### ISSUE TITLE
Cb ThreatHunter API not working

### ISSUE THREAD

**Issue by Idriel** [carbonblack/cbapi-python#234]
Every example queries: host/threathunter/... while now it's host/api/... different queries. 

error;:
  File "/home/user/.local/lib/python2.7/site-packages/cbapi/connection.py", line 188, in http_request
    raise ObjectNotFoundError(uri=uri, message=r.text)
cbapi.errors.ObjectNotFoundError: Received 404 (Object Not Found)

**Comment by avanbrunt-cb** [comment]
@Idriel Can you provide a particular example that is throwing the 404 error?
