### ISSUE TITLE
[BUG] CBR Alert unique_id Not Exposed to GET Query

### ISSUE THREAD

**Issue by jjfallete** [carbonblack/cbapi-python#243]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: Windows
 - Carbon Black Product: CB EDR (Response)
 - Python Version: 2.7

**Describe the bug**
It is not possible to query an alert by unique_id. While each Alert unique_id is exposed when iterating through the results of alerts from a cb.select(Alert) query, attempting to provide the unique_id to the select method returns a nearly empty Alert object, containing only a unique_id data member. Attempting to where() on an Alert select with a valid unique_id returns a 400 "query_syntax_error" from the API.

**Steps to Reproduce**
```python
alert_unique_id = c.select(Alert).first().unique_id  # Find a legitimate Alert unique_id
print (str(alert_unique_id))  # Print alert_unique_id
alert_by_id_1 = c.select(Alert, alert_unique_id)  # Select the alert from the unique_id
print (str(alert_by_id_1))  # Print alert selected from ID - notice it returns only alert_unique_id
alert_by_id_2 = c.select(Alert).where("unique_id:" + str(alert_unique_id))  # Try a where on alert_unique_id instead
print (len(alert_by_id_2))  # Print alert_by_id_2 length to see if it has 1 or more elements, ServerError thrown

# Example: HTTP GET /api/v2/alert?cb.urlver=1&facet=false&q=unique_id%3A92dacdf2-57aa-4276-8fba-871725b6d6ae&rows=1&start=0 took 0.043s (response 400)

 ```

**Expected behavior**
Both of the following would return a single alert object identical to what was returned from c.select(Alert).first()
```python
# Assume alert_unique_id is a valid Alert unique_id
alert_by_id_1 = c.select(Alert, alert_unique_id)
alert_by_id_2 = c.select(Alert).where("unique_id:" + str(alert_unique_id))
 ```

**Screenshots**
N/A

**Additional context**
The inability to do this restricts pulling single Alerts by their ID, which would be useful for product integrations.
This follows emails I had with CB Developer Relations.

**Comment by avanbrunt-cb** [comment]
A fix has been merged this will go out with release 1.7.1
