### ISSUE TITLE
process_cmdline property removed from v2 process search results

### ISSUE THREAD

**Issue by crahan** [carbonblack/cbapi-python#251]
The change to the process search v2 API appears to have removed the `process_cmdline` from Process search results. The only option to now get this information is via `process.summary.process['process_cmdline']` which means performing an additional query based on the `/api/investigate/v1/orgs/{org_key}/processes/summary` API endpoint for each search result that's returned. This slows things down significantly.

In addition, the use of `/api/investigate/v1/orgs/{org_key}/processes/summary` by the Python API (via `process.summary.process['process_cmdline']`) often can not find the requested `process_guid` returned in the Process search results, which results in errors like the following: 

```json
Received 404 (Object Not Found) for https://defense-prod05.conferdeploy.net/api/investigate/v1/orgs/ORGKEY/processes/summary?process_guid=ORGKEY-013e64dd-000029f0-00000000-1d64514443470e9: 
{
    "message":"Resource does not exist",
    "translation_key":"threathunter_resource_does_not_exist",
    "translation_format_values":null
}
```

Manually checkingt the v1 REST API summary endpoint confirms that in the cases where those errors occur the Process with the `process_guid` that is returned from the v2 process search can not be found and throws a 404 error as a result.

Can `process_cmdline` be readded as a field to the v2 process search results so Python scripts do not require the use of additional (expensive) `process.summary.process['process_cmdline']` calls?

**Comment by avanbrunt-cb** [comment]
This is a bug on the Carbon Black Cloud backend and is being fixed soon

**Comment by tlansec** [comment]
Hi,

Apologies if this is a silly question... but is this expected to be resolved already? When making a query to the following API endpoint 

`https://defense-prod05.conferdeploy.net/api/investigate/v2/orgs/{0}/enriched_events/search_jobs
`
& then retrieving via:

`/results`

The "process_cmdline" key is not present in result set. Moreover, the documentation for this endpoint sugggests that this will not be returned:

https://developer.carbonblack.com/reference/carbon-black-cloud/cb-threathunter/latest/process-search-fields/

![image](https://user-images.githubusercontent.com/5901749/90530806-34b23300-e16d-11ea-920d-d77fa6d028de.png)

Thanks,
Tom

**Comment by crahan** [comment]
It's not returned as a field by default I believe, but when you run a v2 process search (https://developer.carbonblack.com/reference/carbon-black-cloud/cb-threathunter/latest/process-search-v2/#start-a-process-search-job), you can specify what additional fields you would like to have returned (e.g. process_cmdline, process_start_time) . For example:

```
"fields": [
    "*",
    "parent_hash",
    "parent_name",
    "process_cmdline",
    "backend_timestamp",
    "device_external_ip",
    "device_group",
    "device_internal_ip",
    "device_os",
    "device_policy",
    "process_effective_reputation",
    "process_reputation,ttp"
    "process_reputation",
    "process_start_time",
    "ttp"
]
```

See also https://github.com/carbonblack/cbapi-python/pull/256/files#diff-547bd1bfe15ddfa9381ad96e4511948aL255-L274 for an example on how this is used in the Cb Python API.

**Comment by tlansec** [comment]
Hi,

Thanks - the link to your code was helpful.

The reason I was confused is that I was using the example POST body from here:

https://developer.carbonblack.com/reference/carbon-black-cloud/cb-threathunter/latest/process-search-v2/#start-an-enriched-events-search-job

Which has:

```
"terms": {
    "fields": [
      "process_username"
    ],
    "rows": 100
  },
```

But really, these keys should be outside of the "terms" dictionary, or they have no effect.

Thanks,
Tom

**Comment by avanbrunt-cb** [comment]
There is a typo in that documentation. We are working to get that updated here is the correct schema for that request
[cid:image001.png@01D67544.2F520A60]

Alex Van Brunt
Member Technical Staff
avanbrunt@vmware.com
<mailto:name@vmware.com>1433 Pearl St, Boulder, CO 80303
[VMware]<http://www.carbonblack.com/>
