### ISSUE TITLE
[BUG]Can't loading the module

### ISSUE THREAD

**Issue by nopvirus** [carbonblack/cbapi-python#257]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: Mac os
 - Carbon Black Product: CB Response
 - Python Version: 2.7

**Describe the bug**
When try to loading the module, show exception.

![image](https://user-images.githubusercontent.com/30836553/88529751-65ee8600-d03b-11ea-8e86-f41ed9f3f837.png)

**Steps to Reproduce**
Steps to reproduce the behavior (Provide a log message if relevant):

**Expected behavior**

**Screenshots**
If applicable, add screenshots or code to help explain your problem.

**Additional context**

**Comment by emitreva-cb** [comment]
Cannot reproduce the issue, please make a fresh install of the cbapi. Closing this issue, reopen if needed.
