### ISSUE TITLE
[BUG] Alert ioc_attr Data Member is of Type Unicode, Not Dict As Expected

### ISSUE THREAD

**Issue by jjfallete** [carbonblack/cbapi-python#260]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: Windows
 - Carbon Black Product: CB EDR (Response)
 - Python Version: 2.7

**Describe the bug**
Alerts containing the ioc_attr data member (alerts of type watchlist.hit.*.process) return it as a unicode object, rather than a dictionary object. It is possible to resolve this by using the ast library method literal_eval() on the returned unicode object.

**Steps to Reproduce**
Steps to reproduce the behavior (Provide a log message if relevant):
```python
import ast
cb = CbResponseAPI()
alerts = cb.select(Alert).where("status:Unresolved")
for alert in alerts:
    if alert.ioc_attr:
        print(str(type(alert.ioc_attr)))  # Outputs: <type 'unicode'>
        print(str(alert.ioc_attr))  # Outputs something like: {"highlights":["PREPREPREprocess.exePOSTPOSTPOST"]}
        print(str(type(ast.literal_eval(alert.ioc_attr))))  # Outputs: <type 'dict'>
        print(str(ast.literal_eval(alert.ioc_attr)))  # Outputs something like: {"highlights":["PREPREPREprocess.exePOSTPOSTPOST"]} 
        break

```

**Expected behavior**
alert.ioc_attr would return a dict object.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by emitreva-cb** [comment]
This is working as expected, to mitigate it you could convert the value to json - print(json.loads(alert.ioc_attr)). Closing the bug.
