### ISSUE TITLE
[BUG] Alert Query with process_id Returns No Results

### ISSUE THREAD

**Issue by jjfallete** [carbonblack/cbapi-python#261]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: Windows
 - Carbon Black Product: CB EDR (Response)
 - Python Version: 2.7

**Describe the bug**
Performing an Alert query with a where() filtering of the process_id always returns no results (empty query). The cbapi.errors.ClientError exception is not thrown (we'd see a 400 query_syntax_error from cbapi.errors.ClientError if the query was invalid).

**Steps to Reproduce**
```python
random_unresolved_alert = cb.select(Alert).where("status:Unresolved AND (alert_type:watchlist.hit.ingress.process OR alert_type:watchlist.hit.query.process)").first()
valid_process_id = random_unresolved_alert.process_id
print(str(valid_process_id))  # Print the process ID from the first selected unresolved process alert

selected_alerts = cb.select(Alert).where("process_id:" + str(valid_process_id ))  # No cbapi.errors.ClientError thrown
print(len(selected_alerts))  # Will always return 0
```

**Expected behavior**
Alerts from the process_id will be returned inside the AlertQuery object.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by avanbrunt-cb** [comment]
Can you provide a traceback for the error? There is not enough information here to diagnose the issue

**Comment by avanbrunt-cb** [comment]
Please reopen with more information
