### ISSUE TITLE
[BUG] Cannot Access process_start_time

### ISSUE THREAD

**Issue by ecooledge** [carbonblack/cbapi-python#262]
**I am seeing this behaviour on:**
 - OS: Win 10
 - Carbon Black Product: CB Defense
 - Python Version: 3.7.3

**Describe the bug**
Can no longer access proc.summary.process['process_start_time'] as suggested in another post. It was working a week and a half ago, but is no longer working.

**Steps to Reproduce**
Steps to reproduce the behavior (Provide a log message if relevant):
Run code:
```python
from cbapi.psc.threathunter import CbThreatHunterAPI
from cbapi.psc.threathunter.models import Event, Process

cb = CbThreatHunterAPI()
query_result = cb.select(Process).where('process_name:cmd.exe')

for process in query_result:
	try:
		print(process.summary.process['process_start_time'])
	except:
		print(process.process_start_time)
```
**Expected behavior**
Either proc.summary.process['process_start_time'] or possibly proc.process_start_time should access the variable for printing or storing. 

**Screenshots**
Errors:
for summary:
        while summary["incomplete_results"]:
    KeyError: 'incomplete_results'
exception option:
    AttributeError: 'Process' object has no attribute 'process_start_time'

Is there a way to access this variable? backend_timestamp works, but is not the time I am looking for. Thanks!

**Comment by avanbrunt-cb** [comment]
@ecooledge Thanks for reporting this bug. We are looking into the change in behavior

**Comment by avanbrunt-cb** [comment]
@ecooledge Are you still experiencing this issue? Can you try with our new SDK https://github.com/carbonblack/carbon-black-cloud-sdk-python if the problem persists can you open a new ticket on the new sdk. Thanks and sorry for the delayed response
