### ISSUE TITLE
[BUG] AttrDict is unmaintained

### ISSUE THREAD

**Issue by tirkarthi** [carbonblack/cbapi-python#263]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: 
 - Carbon Black Product: 
 - Python Version: 3.9

**Describe the bug**

AttrDict is unmaintained and archived with no updates over several years. It might become incompatible with future Python versions over importing ABC from collections directly. Similar to #226 . https://github.com/bcj/AttrDict

```
src/cbapi/auth.py
3:import attrdict
35:class Credentials(attrdict.AttrDict):
```

**Steps to Reproduce**

Tests ran on Python 3.9 generate below warnings : 

```
/root/AttrDict/attrdict/mixins.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping, MutableMapping, Sequence
/root/AttrDict/attrdict/mixins.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping, MutableMapping, Sequence
/root/AttrDict/attrdict/mapping.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```

**Comment by avanbrunt-cb** [comment]
Thanks for the feedback we have fixed this in the newer sdk https://github.com/carbonblack/carbon-black-cloud-sdk-python at the moment we have no plans to fix this here for now
