### ISSUE TITLE
Update Base API to Support non-credential-file proxy settings

### ISSUE THREAD

**Issue by alacercogitatus** [carbonblack/cbapi-python#267]
https://github.com/carbonblack/cbapi-python/blob/a17bcac10bed29840f31e323aa3d74535651aa4c/src/cbapi/connection.py#L363

This line should read: 
`for k in ("ssl_verify", "proxy"):` to allow for passing in the proxy configuration string via the class instantiation for `CbPSCBaseAPI`.

**Comment by abowersox-cb** [comment]
PR#268 resolves this issue.
