### ISSUE TITLE
[BUG] New version 1.7.1 broke alert.save() function

### ISSUE THREAD

**Issue by nguyenl95** [carbonblack/cbapi-python#272]
**I am seeing this behaviour on:**
 - OS: All
 - Carbon Black Product: CB Response
 - Python Version: 3.8

**Steps to Reproduce**
Try resolving alerts with this code. Before [this commit](https://github.com/carbonblack/cbapi-python/commit/e4578da1aed3890615a14ce88671d25f6dc0f54f) the code below works, however >=1.7.1 is broken.
```python
    cb = CbResponseAPI()
    alert_query = cb.select(Alert).where("status:Unresolved")
    
    for alert in alert_query:
        alert.status = 'resolved'
        alert.save()
```

**Comment by nguyenl95** [comment]
I think the problem is the changes on the `refresh` function.

**Comment by nguyenl95** [comment]
Hi @kebringer-cb , are there any problems with this issue? Thanks.

**Comment by avanbrunt-cb** [comment]
@nguyenl95 Can you please provide the error you are seeing?

**Comment by nguyenl95** [comment]
There are no errors in the above code. However, the alert didn't change the status.

**Comment by nguyenl95** [comment]
My Carbonblack version is 7.1.0.200327.1616 btw

**Comment by emitreva-cb** [comment]
Confirming the bug was reproduced and a fix will be provided.

**Comment by nguyenl95** [comment]
Thanks, it works after patching [this one
](https://github.com/carbonblack/cbapi-python/pull/291/commits/4a3e7eb64a5c0bcf53b85247f5eab47a3130f932#diff-d3f70431fa4c469889fe428c47d6599f0e1dab89a64275dc3fee31597d1c7204R300).
