### ISSUE TITLE
[REQUEST] PSC Alerts API: use larger "rows" value by default

### ISSUE THREAD

**Issue by cnotin** [carbonblack/cbapi-python#275]
**I am seeing this behaviour on: (please complete the following information):**
- PSC

**Describe the bug**
I use the PSC Alerts API with code derived from https://github.com/carbonblack/cbapi-python/blob/master/examples/psc/list_cbanalytics_alerts.py and it is a bit slow...

**Steps to Reproduce**
1. Run an alerts search that yield around 1k alerts
2. It takes around 1 minute (contrary to 1 second if we request 1000 rows directly from the API)

**Expected behavior**
The current implementation doesn't set the "rows" parameter and thus currently the API returns pages of 20 results. Iterating on 20 rows chunks is very slow contrary to 50 (default in UI) or more, this is similar to https://github.com/carbonblack/cbapi-python/pull/252/.

Moreover this Python API doesn't offer to change this value.

**Comment by avanbrunt-cb** [comment]
PR merged
