### ISSUE TITLE
[SUGGESTION] Is this library going to be replaced by "carbon-black-cloud-sdk-python"?

### ISSUE THREAD

**Issue by cnotin** [carbonblack/cbapi-python#278]
I have been informed of a new library currently in alpha https://github.com/carbonblack/carbon-black-cloud-sdk-python

Can you please advise on which one to use for a new development?
If I may suggest, if you are going to move all development efforts to the new one, I suggest making it clear on this repo so that people know where to work in priority and suggest PRs :)

**Comment by avanbrunt-cb** [comment]
@cnotin Thanks for the feedback. The https://github.com/carbonblack/carbon-black-cloud-sdk-python repo is going to be the path forwards for the Carbon Black Cloud. EDR and App Control will remain on cbapi. I'll look into adding some notice on the readme to make this more clear

**Comment by cnotin** [comment]
Thanks! I let you close this whenever you want.
