### ISSUE TITLE
[BUG] Alert Query with process_id Returns No Results #261

### ISSUE THREAD

**Issue by jjfallete** [carbonblack/cbapi-python#281]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: Windows
 - Carbon Black Product: CB EDR (Response)
 - Python Version: 2.7 / 3.7

**Describe the bug**
Performing an Alert query with a where() filtering of the process_id always returns no results (empty query). The cbapi.errors.ClientError exception is not thrown (we'd see a 400 query_syntax_error from cbapi.errors.ClientError if the query was invalid).

**Steps to Reproduce**
```python
random_unresolved_alert = cb.select(Alert).where("status:Unresolved AND (alert_type:watchlist.hit.ingress.process OR alert_type:watchlist.hit.query.process)").first()
valid_process_id = random_unresolved_alert.process_id
print(str(valid_process_id))  # Print the process ID from the first selected unresolved process alert

selected_alerts = cb.select(Alert).where("process_id:" + str(valid_process_id ))  # No cbapi.errors.ClientError thrown
print(len(selected_alerts))  # Will always return 0
```

**Expected behavior**
Alerts from the process_id will be returned inside the AlertQuery object.

**Screenshots**
N/A

**Additional context**
My original issue #261 was closed abruptly for, "Can you provide a traceback for the error? There is not enough information here to diagnose the issue" -- there is no error (see description for more). I also provided steps to reproduce. If more information is needed, please let me know and I can provide more or we can schedule a call to discuss. Thanks!

**Comment by avanbrunt-cb** [comment]
@jjfallete Sorry for the delay can you make a support case https://www.carbonblack.com/support/

**Comment by avanbrunt-cb** [comment]
Please reach out if your problem was not addressed through support
