### ISSUE TITLE
Listing Error with sensor_group_operations.py

### ISSUE THREAD

**Issue by TheHmadQureshi** [carbonblack/cbapi-python#285]
Hi,

While listing sensor groups using **sensor_group_operations.py** i am getting an error. 

![image](https://user-images.githubusercontent.com/9057459/105023485-102fef00-5a5c-11eb-8066-541c6dedc8ba.png)

The script returns **435** results before this the index goes out of range. This is the command line i am using:

![image](https://user-images.githubusercontent.com/9057459/105023573-2e95ea80-5a5c-11eb-8d98-33f77428559f.png)

Anyone else faced this issue? possible mitigations?

**Comment by emitreva-cb** [comment]
We will release an updated version of the script to fix the issue. In the meantime you could change:
this line:
print("  {0:40}{1:18}{2}".format(sensor.hostname, ipaddrs[0], sensor.last_checkin_time))
to:
print("  {0:40}{1:18}{2}".format(sensor.hostname, ipaddrs[0] if len(ipaddrs) else '', sensor.last_checkin_time))

If this fixes the issue, please close the bug.

**Comment by emitreva-cb** [comment]
This should be fixed with the new release 1.7.4.
