### ISSUE TITLE
[BUG] Received error code 500 from API: Unhandled exception: local variable '_session' referenced before assignment

### ISSUE THREAD

**Issue by atomisotope** [carbonblack/cbapi-python#290]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: Centos 7
 - Carbon Black Product: 7.3.0.201016.1331
 - Python Version: 2.7.5

**Describe the bug**
Receiving a ServerError: Received error code 500 from API: Unhandled exception: local variable '_session' referenced before assignment

**Steps to Reproduce**
Steps to reproduce the behavior (Provide a log message if relevant):
1. Using the cbapi create a lr_session() to a host using the response modules like below.
2.  
`from cbapi.response import *

c = CbEnterpriseResponseAPI()

sensor = c.select(Sensor).where('hostname:TEST'[0]

session = sensor.lr_session()`
3. Instantly receive the above error.

**Expected behavior**
A live response session to be created with no errors.

**Comment by atomisotope** [comment]
Hello,

I was wondering if anyone was able to reproduce this error. Or was this a problem on my end?

Thanks!

**Comment by emitreva-cb** [comment]
Hello,

The only issue I am seeing is that there is a missing closing parenthesis in one of the statements:
sensor = c.select(Sensor).where('hostname:TEST'[0]
should be:
sensor = c.select(Sensor).where('hostname:TEST')[0]

otherwise I was unable to reproduce the issue.

**Comment by atomisotope** [comment]
Yes that was a typo. it was a configuration issue and I was able to figure it out. 

Thanks!
