### ISSUE TITLE
[BUG] Unable to connect to server without an admin token

### ISSUE THREAD

**Issue by sevdog** [carbonblack/cbapi-python#303]
**I am seeing this behaviour on: (please complete the following information):**
 - OS: any
 - Carbon Black Product: CB Response (EDR) 7.6.0
 - Python Version: any
**Describe the bug**
When using a "non-admin" API-token is not possible to connect to CB Response via this client.

```python
cbapi = CbReponseAPI(url=device_url, token=token, ssl_verify=False)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cbapi/response/rest_api.py", line 53, in __init__
    legacy_partitions = [p for p in self.select(StoragePartition) if p.info.get("isLegacy", False)]
  File "/usr/local/lib/python3.8/site-packages/cbapi/response/rest_api.py", line 53, in <listcomp>
    legacy_partitions = [p for p in self.select(StoragePartition) if p.info.get("isLegacy", False)]
  File "/usr/local/lib/python3.8/site-packages/cbapi/query.py", line 141, in _perform_query
    for item in self.results:
  File "/usr/local/lib/python3.8/site-packages/cbapi/response/models.py", line 102, in results
    for k, v in iteritems(self._cb.get_object(self._urlobject, default={})):
  File "/usr/local/lib/python3.8/site-packages/cbapi/connection.py", line 428, in get_object
    result = self.api_json_request("GET", uri)
  File "/usr/local/lib/python3.8/site-packages/cbapi/connection.py", line 492, in api_json_request
    result = self.session.http_request(method, uri, headers=headers, data=raw_data, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cbapi/connection.py", line 293, in http_request
    raise ClientError(error_code=r.status_code, message=r.text)
cbapi.errors.ClientError: Received error code 403 from API:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.</p> 
```

**Steps to Reproduce**
Steps to reproduce the behavior (Provide a log message if relevant):
1. Select/create a user without "global admin"
![Schermata da 2021-12-15 12-41-17](https://user-images.githubusercontent.com/13779643/146180263-cc709814-ffd6-4df8-961a-45d23ee7988c.png)
2. Generate an API-token for that user
3. Instantiate `CbReponseAPI` with this API-token

**Expected behavior**
The client should be connected correctly and not exceptions should be thrown.

**Additional context**
In previous server versions even "non-admin" users could be used to connect via API with this client.

CB Response 7.6.0 [release notes](https://docs.vmware.com/en/VMware-Carbon-Black-EDR/7.6.0/rn/vmware-carbon-black-edr-server-760-release-notes/index.html).

**Comment by fslds** [comment]
I added a PR (#304) which should resolve this issue. If it will be accepted in the current form by the developers is another question. 

I fixed it locally by commenting out the bad lines earlier this week, but now it is more 'elegant' with a try/except block. 
If you trust me (always verify 😉) one can install the patched version easily, with `pip install git+https://github.com/fslds/cbapi-python/#egg=cbapi`  to regain functionality. You can also clone and install locally or edit your already installed version similarly.

**Comment by kebringer-cb** [comment]
Appreciate the PR - we'll review it.  Thanks.

**Comment by fslds** [comment]
Any idea on when this will be merged and released in a new version? I imagine it breaks a lot of automation and workflows for users, or at least it does in our case... (Or is everyone using an administrative user the whole time? [_nervous laughter_]).

**Comment by kebringer-cb** [comment]
It's on the develop branch and we'll do a release to pypi today.

**Comment by kebringer-cb** [comment]
v1.7.6 has been released with this fix.
Master branch and pypi: https://pypi.org/project/cbapi/1.7.6/
Any problems, please let us know.
Thanks for your contribution to get this fixed.
