### ISSUE TITLE
AttributeError: 'Binary' object has no attribute 'digsig publisher'

### ISSUE THREAD

**Issue by jscarpaciCB** [carbonblack/cbapi-python#43]
When attempting to use the binary_search example script I get the following error:

Traceback (most recent call last):
  File "C:\Users\jscarpaci\PycharmProjects\untitled\binary_search.py", line 38,
in <module>
    sys.exit(main())
  File "C:\Users\jscarpaci\PycharmProjects\untitled\binary_search.py", line 25,
in main
    print("%-20s : %s" % ('Publisher', binary.digsig_publisher))
  File "C:\Python27\lib\site-packages\cbapi\oldmodels.py", line 130, in __getatt
r__
    return super(BaseModel, self).__getattribute__(attrname)
AttributeError: 'Binary' object has no attribute 'digsig_publisher'

I tried making this conditional based on binary.signed == 'True' but that didn't work.

**Comment by jscarpaciCB** [comment]
Fixed by doing conditional statement right:

line22:        print("%-20s : %s" % ('Publisher', binary.digsig_publisher) if binary.signed == True else "%-20s : %s" % ('Publisher', 'n/a'))

Now returns output like below for unsigned binaries:

FE643B5B7CCA55B39CB081D2B2C5333C
--------------------------------------------------------------------------------

Size (bytes)         : 11438691
Signature Status     : False
Publisher            : n/a
Product Name         : Adobe Acrobat Forms
Product Version      : 10.0.0.396
File Version         : 10.0.0.396
64-bit (x64)         : False
EXE                  : False
On-Disk Filename     : acroform.api

**Comment by jgarman** [comment]
This will be addressed in 0.9.7
