### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by rawtalent06** [carbonblack/cbapi-python#48]
I was originally have the same issue from #20, but upgrading resolved that.  However, after upgrading I am now seeing the following error message:  TypeError: can't compare offset-naive and offset-aware datetimes.

File "event_export.py", line 80, in write_csv
    for event in proc.all_events:
  File "/usr/local/lib/python2.7/site-packages/cbapi/response/models.py", line 1221, in all_events
    list(self.children) + list(self.regmods) + list(self.crossprocs))
  File "/usr/local/lib/python2.7/site-packages/cbapi/response/models.py", line 1330, in __lt__
    return self.timestamp < other.timestamp
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by jgarman** [comment]
Thanks for your patience, @rawtalent06 - I'll take a look at this for 0.9.8.

**Comment by jgarman** [comment]
This should be addressed in 0.9.8
