### ISSUE TITLE
Feature Request: Download Compressed Binary

### ISSUE THREAD

**Issue by austinbyers** [carbonblack/cbapi-python#62]
Using the [API](https://github.com/carbonblack/cbapi/tree/master/client_apis#apiv1binarymd5) (or the web UI), the binary you download from CarbonBlack is `.zip` compressed.

From what I can tell, the Python library automatically decompresses when it exposes the `binary.file` object. Is there any way (via Python library) to download the compressed binary directly?

**Comment by jgarman** [comment]
There is no way directly to do this... but you can reach directly into the "session" and grab it - something like the following (assuming your `CbResponseAPI` object is named `c`):

```
d=c.session.get("/api/v1/binary/BF93A2F9901E9B3DFCA8A7982F4A9868").content
```
