### ISSUE TITLE
Cb Response server does not properly escape non-BMP unicode in event data

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cbapi-python#65]
Cb Response sends data like "\U0001f30e" for U+1f30e http://www.charbase.com/1f30e-unicode-earth-globe-americas instead of the UTF-8 surrogate pairs. Technically this is in violation of JSON and thus the JSON parser chokes on the input.

**Comment by avanbrunt-cb** [comment]
Closing due to outdated status. Please reopen if still a concern
