### ISSUE TITLE
Printing out the generator object's data

### ISSUE THREAD

**Issue by mbabatunde** [carbonblack/cbapi-python#73]
Hi!

Currently using the API rn and I was wondering if there was a way to return the actual value of the generator object from the netconns function. Currently, my code is just returning the generator object and not a value that I can interpret. Current code rn:
```python
import logging
root = logging.getLogger()
root.addHandler(logging.StreamHandler())
logging.getLogger("cbapi").setLevel(logging.DEBUG)

from cbapi.response import *
cb = CbResponseAPI()

query = cb.select(Process).where("netconn_count:[1 TO *] and ipaddr:*")
for proc in query:
    print(proc.netconns)
```
Output:
```
<generator object netconns at 0x107bfda40>
<generator object netconns at 0x107bfda40>
<generator object netconns at 0x107bfda40>
<generator object netconns at 0x107bfda40>
(continues)
```

The documentation for the API says it returns the generator object, but I was wondering if there were any examples or suggestions for what I can do.

**Comment by jgarman** [comment]
You just have to loop over the result of netconns:

```
for netconn in proc.netconns:
    print netconn.remote_ip, netconn.remote_port
```

**Comment by mbabatunde** [comment]
@jgarman Thank you, this worked! Is there any documentation on the remote_ip or remote_port methods in the API documentation?

**Comment by jgarman** [comment]
Unfortunately there are no good docs- but you can always "print" out a netconn event and get the list of attributes, for example:

```
Cb Network Connection event:
timestamp            : 2017-07-11 13:35:04.447000
domain               : weather.tile.appex.bing.com
remote_ip            : 65.202.184.41
remote_port          : 80
proto                : IPPROTO_TCP
direction            : Outbound
local_ip             : 172.22.5.141
local_port           : 50042
proxy_ip             : 0.0.0.0
proxy_port           : 0
```

**Comment by mbabatunde** [comment]
I see. Thank you!
