### ISSUE TITLE
Max retries with URL

### ISSUE THREAD

**Issue by mbabatunde** [carbonblack/cbapi-python#74]
Hi again!

I switched to Python 2.7.13 and upgraded the six module to 1.10.0. Each time I try to make a instance of the CbResponseAPI call when testing it out, I get this error (I removed the host and port for security reasons):
```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cbapi.response import *
>>> c = CbResponseAPI()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cbapi/response/rest_api.py", line 66, in __init__
    self.server_info = self.info()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cbapi/response/rest_api.py", line 92, in info
    r = self.session.get("/api/info")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cbapi/connection.py", line 157, in get
    return self.http_request("GET", url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cbapi/connection.py", line 143, in http_request
    original_exception=connection_error)
cbapi.errors.ApiError: Received a network connection error from : HTTPSConnectionPool(host='', port=): Max retries exceeded with url: /api/info (Caused by ProtocolError('Connection aborted.', error(54, 'Connection reset by peer')))
```
When I ran ```cbapi-response configure```, everything works out and it successfully writes credentials to the credentials.response file. When I did all of this with python3, everything worked and connected to the host with no issues. Is there still an issue with python2 and the API bindings or is there something I'm doing wrong?

**Comment by jgarman** [comment]
That's a great question - we have seen this with older Python versions where they default to an older version of TLS to connect to hosts. Try installing the "security" option in the requests module: `pip install requests[security]` and see if that clears it up.

**Comment by mbabatunde** [comment]
Hi @jgarman! Sorry for this late reply, but I actually just reinstalled the cbapi and it worked somehow. Unsure how to duplicate the issue, but it was interesting. Thanks for the suggestion though!
