### ISSUE TITLE
RuntimeError: No active exception to reraise

### ISSUE THREAD

**Issue by psilberman** [carbonblack/cbapi-python#88]
Hey @jgarman,

This line https://github.com/carbonblack/cbapi-python/blob/master/src/cbapi/models.py#L221 is causes in a RuntimeError exception because its raising when there is no exception. I'm not sure how you want to handle this? . It seems like returning None or raising an AttributeError are viable options. Thoughts?

**Comment by jgarman** [comment]
Hmm... I thought that would "raise" an AttributeError for me... I guess that was wrong. I'm going to experiment here and come up with a solution.

**Comment by jgarman** [comment]
Interested in your thoughts @psilberman - I just mimicked what the Python interpreter returns when an attribute is missing from a typical object. The `.get()` method can be used to try and retrieve an attribute with a default value

**Comment by psilberman** [comment]
Yup, this change makes sense to me.
-peter
