### ISSUE TITLE
Cannot retrieve fileCatalog.publisher

### ISSUE THREAD

**Issue by jbmfg** [carbonblack/cbapi-python#92]
When requesting fileCatalog.x you get the x field that the fileCatalog makes available. However, when you try to access fileCatalog.publisher you get an empty response from cbapi.protection.models.Publisher :

`comps = api.select(Computer).where("deleted:false") for c in comps: 
files = c.fileInstances.where("fileName:winscp.exe") 
for f in files: print f.fileCatalog.company # returns the expected company field 
print f.fileCatalog.publisher # returns cbapi.protection.models.Publisher:`

**Comment by jgarman** [comment]
Ah this is because we're using the `publisherId` field to "join" the FileCatalog object with the Publisher object.

We will back this out... in the mean time you can use `.get("publisher")` on the `f` object to get the publisher string directly.

**Comment by avanbrunt-cb** [comment]
Closing due to outdated status. Please reopen if still a concern
