### ISSUE TITLE
API Object to grab "Files on Computers"

### ISSUE THREAD

**Issue by SMaiorino** [carbonblack/cbapi-python#98]
Hello,
I've been fiddling with this for a while and still can't seem to figure it out...is there any way to use the CB Protection API to grab files from the "Files on Computers" tab within the protect client? 

See attached screenshot

![files_on_comps](https://user-images.githubusercontent.com/28761056/35154751-5e7529d2-fcf9-11e7-8ff7-4c3326e8e456.PNG)

**Comment by jgarman** [comment]
I believe this may be the FileUpload model object?
 https://developer.carbonblack.com/reference/enterprise-protection/8.0/rest-api/#fileupload

**Comment by SMaiorino** [comment]
File Upload I believe is for files uploaded to the server. This tab under "Assets --> Files" shows all files on computers that have the protect agent installed in our environment. 

I can't find a simple way to access these files through the API since there isn't a criteria such as "endpoint that contains this file".

**Comment by avanbrunt-cb** [comment]
Closing due to outdated status. Please reopen if still a concern
